### PR TITLE
Added dockerfile and fixed pytube issue

### PR DESCRIPTION
**Pull request by Adam-Shea**
Installs pytube from fixed pull request. Should be updated later when new version gets pushed to pip.
Added docker file so docker image can be built
Can now accept links using `youtu.be/` and `youtube.com/shorts`

I am interested in building an action that will move cassette into github packages to enable easier docker use

### CODE REVIEW

**Comment by lohanjs** [comment]
Thanks for the contribution! Comment when you want it merged.

**Comment by Adam-Shea** [comment]
It should be ready to merge straight away.
Could we communicate further to discuss creating a github action to generate docker images?

**Comment by lohanjs** [comment]
To be honest, the Docker and Actions additions, while useful, go beyond the scope of my project. The original intent was to provide a base for a Discord music bot for others, since I was struggling to find working code myself.

**Comment by Adam-Shea** [comment]
Ahhh gotcha. That's fair enough :)

**Pull request closed without merging**
